# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  menu: 'list'
  page: 'setting'
  tasks:
    Alas:
      - Playwright
      - Error
      - Optimization
      - ProfileSettings
    Restart:
      - Scheduler

# ==================== Chore ====================

Chore:
  menu: list
  page: setting
  tasks:
    PetCares:
      - Scheduler
      - PetCares
    BankInterest:
      - Scheduler
      - NeopianBank
    PetTraining:
      - Scheduler
      - PetTraining
    DailyQuest:
      - Scheduler
      - DailyQuest
    BattleDome:
      - Scheduler
      - BattleDome
    AltadorCouncil:
      - Scheduler
    AnchorManagement:
      - Scheduler
    AppleBobbing:
      - Scheduler
    ColtzansShrine:
      - Scheduler
    DailyPuzzle:
      - Scheduler
    DesertedTomb:
      - Scheduler
    FaerieCrossword:
      - Scheduler
    Fishing:
      - Scheduler
      - Fishing
    ForgottenShore:
      - Scheduler
    FruitMachine:
      - Scheduler
    GiantJelly:
      - Scheduler
    GiantOmelette:
      - Scheduler
    GraveDanger:
      - Scheduler
    GrumpyKing:
      - Scheduler
    LunarTemple:
      - Scheduler
    MeteorCrashSite:
      - Scheduler
    MoltaraQuarry:
      - Scheduler
    NeggCave:
      - Scheduler
    PotatoCounter:
      - Scheduler
    QasalanExpellibox:
      - Scheduler
    RichSlorg:
      - Scheduler
    Snowager:
      - Scheduler
    TDMBGPOP:
      - Scheduler
    Tombola:
      - Scheduler
    TrudysSurprise:
      - Scheduler
    WiseKing:
      - Scheduler
    HealingSpring:
      - Scheduler
      - HealingSpring
    MonthlyFreebies:
      - Scheduler
    StockMarket:
      - Scheduler
      - StockMarket
    WishingWell:
      - Scheduler
      - WishingWell
    Scratchcard:
      - Scheduler
      - Scratchcard
    AlmostAbandonedAttic:
      - Scheduler
      - AlmostAbandonedAttic
    IglooGarageSale:
      - Scheduler
      - IglooGarageSale
    EssenceCollection:
      - Scheduler
    WheelOfCelebration:
      - Scheduler


# ==================== Games ====================

Games:
  menu: 'list'
  page: 'setting'
  tasks:
    FashionFever:
      - Scheduler

# ==================== Utility ====================
Utility:
  menu: 'list'
  page: 'setting'
  tasks:
    QuickStock:
      - Scheduler
      - QuickStock
    Restocking:
      - Scheduler
      - Restocking
    ShopWizard:
      - Scheduler
      - ShopWizard
    Auction:
      - Scheduler
      - Auction
    VoidsWithin:
      - Scheduler
      - VoidsWithin
    InventoryTool:
      - PlayerStorage
    SafetyDepositBox:
      - Scheduler
      - SafetyDepositBox

# ==================== Tool ====================

Tool:
  menu: 'list'
  page: 'tool'
  tasks: {}
